export interface DemoListing {
  id: string;
  title: string;
  city: string;
  state: string;
  zip_code: string;
  lat: number;
  lng: number;
  description: string;
  price_per_day: number;
  price_per_month: number;
  size_sqft: number;
  space_type:
    | 'parking_lot'
    | 'storefront'
    | 'vacant_land'
    | 'warehouse'
    | 'other'
    | 'storage_unit'
    | 'garage'
    | 'food_truck_vending'
    | 'food_truck_storage'
    | 'mobile_vendor'
    | 'commissary_kitchen'
    | 'office';
  use_type?: ('personal' | 'commercial' | 'events')[];
  images: { image_url: string }[];
  amenities: {
    electricity: boolean;
    water_access: boolean;
    restrooms: boolean;
    parking: boolean;
    wifi: boolean;
    garbage_access: boolean;
  };
  rating: number;
  review_count: number;
  instant_book: boolean;
  featured: boolean;
}

export const DEMO_LISTINGS: DemoListing[] = [
  // ── Original US listings ─────────────────────────────────────────────────
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567801',
    title: 'Corner Lot – Perfect for Food Trucks · Austin',
    city: 'Austin', state: 'TX', zip_code: '78701',
    lat: 30.2672, lng: -97.7431,
    description: 'High-visibility corner lot in the heart of downtown Austin, just two blocks from Sixth Street. Electricity and water hookups on-site. Ideal for food trucks, pop-ups, or weekend markets.',
    price_per_day: 120, price_per_month: 2200, size_sqft: 1800,
    space_type: 'parking_lot', use_type: ['commercial', 'events'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=800' }, { image_url: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800' }],
    amenities: { electricity: true, water_access: true, restrooms: false, parking: true, wifi: false, garbage_access: true },
    rating: 4.8, review_count: 94, instant_book: true, featured: true,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567802',
    title: 'Boutique Storefront on Broadway · Nashville',
    city: 'Nashville', state: 'TN', zip_code: '37203',
    lat: 36.1627, lng: -86.7816,
    description: 'Charming 950 sqft storefront with exposed brick and floor-to-ceiling windows in the Gulch neighborhood. Perfect for pop-up retail, tasting events, or brand activations.',
    price_per_day: 200, price_per_month: 3800, size_sqft: 950,
    space_type: 'storefront', use_type: ['commercial', 'events'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800' }, { image_url: 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800' }],
    amenities: { electricity: true, water_access: true, restrooms: true, parking: false, wifi: true, garbage_access: true },
    rating: 4.9, review_count: 57, instant_book: false, featured: true,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567803',
    title: 'Covered Market Stall – Pearl District · Portland',
    city: 'Portland', state: 'OR', zip_code: '97209',
    lat: 45.5051, lng: -122.6750,
    description: 'Covered 400 sqft stall in the vibrant Pearl District with consistent foot traffic year-round. Fully permitted for food vendors. Water and power included.',
    price_per_day: 95, price_per_month: 1600, size_sqft: 400,
    space_type: 'other', use_type: ['commercial', 'events'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800' }, { image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800' }],
    amenities: { electricity: true, water_access: true, restrooms: true, parking: false, wifi: true, garbage_access: true },
    rating: 4.7, review_count: 112, instant_book: true, featured: true,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567804',
    title: 'Riverside Vacant Lot – Great Views · Denver',
    city: 'Denver', state: 'CO', zip_code: '80202',
    lat: 39.7392, lng: -104.9903,
    description: 'Open 3,200 sqft lot along the South Platte River with panoramic mountain views. Zoned commercial. Ideal for seasonal events, markets, or food truck gatherings.',
    price_per_day: 150, price_per_month: 2800, size_sqft: 3200,
    space_type: 'vacant_land', use_type: ['commercial', 'events'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800' }, { image_url: 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3df1?w=800' }],
    amenities: { electricity: true, water_access: false, restrooms: false, parking: true, wifi: false, garbage_access: true },
    rating: 4.5, review_count: 38, instant_book: false, featured: true,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567805',
    title: 'Beachside Pop-Up Lot · Miami',
    city: 'Miami', state: 'FL', zip_code: '33139',
    lat: 25.7617, lng: -80.1918,
    description: 'Sun-drenched 1,100 sqft paved lot two blocks from South Beach. High weekend traffic. Restrooms and electricity nearby. Perfect for dessert trucks, juice bars, or retail pop-ups.',
    price_per_day: 185, price_per_month: 3500, size_sqft: 1100,
    space_type: 'parking_lot', use_type: ['commercial', 'events'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800' }, { image_url: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800' }],
    amenities: { electricity: true, water_access: true, restrooms: true, parking: true, wifi: false, garbage_access: true },
    rating: 4.6, review_count: 73, instant_book: true, featured: false,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567806',
    title: 'Warehouse Loading Bay – Pilsen · Chicago',
    city: 'Chicago', state: 'IL', zip_code: '60608',
    lat: 41.8781, lng: -87.6298,
    description: 'Spacious 4,800 sqft warehouse with two loading docks in the arts-forward Pilsen neighborhood. High ceilings, 3-phase power. Great for production kitchens, wholesale vendors, or light manufacturing.',
    price_per_day: 250, price_per_month: 4500, size_sqft: 4800,
    space_type: 'warehouse', use_type: ['commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1555244162-803834f70033?w=800' }, { image_url: 'https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?w=800' }],
    amenities: { electricity: true, water_access: true, restrooms: true, parking: true, wifi: true, garbage_access: true },
    rating: 4.4, review_count: 29, instant_book: false, featured: false,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567807',
    title: 'Pike Place–Adjacent Market Spot · Seattle',
    city: 'Seattle', state: 'WA', zip_code: '98101',
    lat: 47.6062, lng: -122.3321,
    description: 'Premium 600 sqft outdoor stall one block from Pike Place Market. Exceptional tourist foot traffic daily. Water and power included. Health permit pre-approved for food vendors.',
    price_per_day: 165, price_per_month: 3000, size_sqft: 600,
    space_type: 'other', use_type: ['commercial', 'events'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800' }, { image_url: 'https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=800' }],
    amenities: { electricity: true, water_access: true, restrooms: true, parking: false, wifi: false, garbage_access: true },
    rating: 4.9, review_count: 88, instant_book: true, featured: false,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567808',
    title: 'SoHo Ground-Floor Retail Space · New York',
    city: 'New York', state: 'NY', zip_code: '10013',
    lat: 40.7128, lng: -74.0060,
    description: 'Iconic 1,250 sqft ground-floor retail space in the heart of SoHo with 18-ft ceilings and original hardwood floors. Perfect for high-end pop-ups, brand launches, or showroom rentals.',
    price_per_day: 300, price_per_month: 5000, size_sqft: 1250,
    space_type: 'storefront', use_type: ['commercial', 'events'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800' }, { image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800' }],
    amenities: { electricity: true, water_access: false, restrooms: true, parking: false, wifi: true, garbage_access: true },
    rating: 4.8, review_count: 61, instant_book: false, featured: false,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567809',
    title: 'Sunset Strip Food Court Slot · Los Angeles',
    city: 'Los Angeles', state: 'CA', zip_code: '90028',
    lat: 34.0522, lng: -118.2437,
    description: 'Busy 800 sqft end-cap spot in an established food truck court on the Sunset Strip. Steady evening crowd from nearby entertainment venues. All utilities included.',
    price_per_day: 175, price_per_month: 3200, size_sqft: 800,
    space_type: 'parking_lot', use_type: ['commercial', 'events'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800' }, { image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800' }],
    amenities: { electricity: true, water_access: true, restrooms: true, parking: true, wifi: true, garbage_access: true },
    rating: 4.7, review_count: 105, instant_book: true, featured: false,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567810',
    title: 'Deep Ellum Event Lot · Dallas',
    city: 'Dallas', state: 'TX', zip_code: '75226',
    lat: 32.7767, lng: -96.7970,
    description: 'Fully fenced 2,400 sqft gravel lot in Deep Ellum entertainment district. High bar-hopping crowd on weekends. Power pedestal, dumpster, and security lighting included.',
    price_per_day: 130, price_per_month: 2400, size_sqft: 2400,
    space_type: 'vacant_land', use_type: ['commercial', 'events'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3df1?w=800' }, { image_url: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800' }],
    amenities: { electricity: true, water_access: false, restrooms: false, parking: true, wifi: false, garbage_access: true },
    rating: 4.3, review_count: 45, instant_book: true, featured: false,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567811',
    title: 'Scottsdale Farmers Market Pad · Phoenix',
    city: 'Phoenix', state: 'AZ', zip_code: '85251',
    lat: 33.4484, lng: -112.0740,
    description: 'Shaded 500 sqft concrete pad in a busy weekend farmers market in Old Town Scottsdale. Water and power at each stall. Great for specialty food vendors and artisan crafts.',
    price_per_day: 80, price_per_month: 1400, size_sqft: 500,
    space_type: 'other', use_type: ['commercial', 'events'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=800' }, { image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800' }],
    amenities: { electricity: true, water_access: true, restrooms: true, parking: true, wifi: false, garbage_access: true },
    rating: 4.6, review_count: 52, instant_book: true, featured: false,
  },
  {
    id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567812',
    title: 'Ponce City Market Adjacent Lot · Atlanta',
    city: 'Atlanta', state: 'GA', zip_code: '30308',
    lat: 33.7490, lng: -84.3880,
    description: 'Prime 1,600 sqft paved lot steps from Ponce City Market and the BeltLine. High foot and bike traffic. Electricity available. Perfect for upscale food trucks and pop-up retail.',
    price_per_day: 140, price_per_month: 2600, size_sqft: 1600,
    space_type: 'parking_lot', use_type: ['commercial', 'events'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1567521464027-f127ff144326?w=800' }, { image_url: 'https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?w=800' }],
    amenities: { electricity: true, water_access: true, restrooms: false, parking: true, wifi: false, garbage_access: true },
    rating: 4.5, review_count: 67, instant_book: false, featured: false,
  },

  // ── Utah County listings ─────────────────────────────────────────────────
  {
    id: 'ut-1',
    title: 'Climate-Controlled Storage Unit',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2338, lng: -111.6585,
    description: 'Spacious storage unit perfect for furniture, seasonal items, or business inventory. 24/7 access with security cameras.',
    price_per_day: 5, price_per_month: 150, size_sqft: 200,
    space_type: 'storage_unit', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1694601618351-dbbbb2b8934f?w=1080' }],
    amenities: { electricity: false, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.8, review_count: 24, instant_book: true, featured: true,
  },
  {
    id: 'ut-2',
    title: 'Covered Parking Spot',
    city: 'Orem', state: 'UT', zip_code: '84057',
    lat: 40.2969, lng: -111.6946,
    description: 'Secure covered parking in downtown area. Perfect for daily commuters. Easy access and well-lit.',
    price_per_day: 7, price_per_month: 200, size_sqft: 120,
    space_type: 'parking_lot', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1604063155785-ee4488b8ad15?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: false, parking: true, wifi: false, garbage_access: false },
    rating: 4.9, review_count: 31, instant_book: true, featured: false,
  },
  {
    id: 'ut-3',
    title: 'Large Warehouse Space',
    city: 'Lehi', state: 'UT', zip_code: '84043',
    lat: 40.3916, lng: -111.8508,
    description: 'Commercial warehouse space ideal for inventory storage or light manufacturing. Loading dock available.',
    price_per_day: 40, price_per_month: 1200, size_sqft: 2000,
    space_type: 'warehouse', use_type: ['commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1771530789155-b1f03fbf82b5?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: false, parking: true, wifi: false, garbage_access: false },
    rating: 4.7, review_count: 18, instant_book: false, featured: true,
  },
  {
    id: 'ut-4',
    title: 'Garage Storage Bay',
    city: 'American Fork', state: 'UT', zip_code: '84003',
    lat: 40.3769, lng: -111.7957,
    description: 'Clean and dry garage bay perfect for vehicle storage, tools, or seasonal equipment.',
    price_per_day: 6, price_per_month: 180, size_sqft: 288,
    space_type: 'garage', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1758448721161-7b3df5ec04b3?w=1080' }],
    amenities: { electricity: true, water_access: true, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.6, review_count: 12, instant_book: true, featured: false,
  },
  {
    id: 'ut-5',
    title: 'Food Truck Vending – Event Venue',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2290, lng: -111.6579,
    description: 'Prime food truck vending space at busy event venue. Perfect for active food service with access to electricity and water hookups. High foot traffic during weekend markets and concerts.',
    price_per_day: 8, price_per_month: 250, size_sqft: 800,
    space_type: 'food_truck_vending', use_type: ['events', 'commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1638132704714-4156222cb2cd?w=1080' }],
    amenities: { electricity: true, water_access: true, restrooms: false, parking: false, wifi: false, garbage_access: true },
    rating: 4.9, review_count: 45, instant_book: false, featured: true,
  },
  {
    id: 'ut-6',
    title: 'Mobile Vendor Spot – Downtown',
    city: 'Orem', state: 'UT', zip_code: '84057',
    lat: 40.2777, lng: -111.7005,
    description: 'Premium mobile vendor space in busy downtown area. Perfect for food trucks, coffee carts, or retail vendors. Located near offices and retail for lunch service Monday–Friday.',
    price_per_day: 6, price_per_month: 175, size_sqft: 450,
    space_type: 'mobile_vendor', use_type: ['events', 'commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1774557936886-84837289433d?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.7, review_count: 28, instant_book: true, featured: false,
  },
  {
    id: 'ut-7',
    title: 'Festival Grounds Vending Space',
    city: 'Saratoga Springs', state: 'UT', zip_code: '84045',
    lat: 40.3491, lng: -111.9047,
    description: 'Premium vending location at popular festival grounds. Ideal for food trucks and mobile vendors. Multiple events throughout the year including farmers markets, music festivals, and holiday celebrations.',
    price_per_day: 10, price_per_month: 300, size_sqft: 1125,
    space_type: 'food_truck_vending', use_type: ['events', 'commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1777817530549-d72109ff6294?w=1080' }],
    amenities: { electricity: true, water_access: true, restrooms: false, parking: false, wifi: false, garbage_access: true },
    rating: 5.0, review_count: 52, instant_book: false, featured: true,
  },
  {
    id: 'ut-8',
    title: 'Shared Commissary Kitchen – Full Service',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2444, lng: -111.6391,
    description: 'Professional licensed commissary kitchen with all commercial-grade equipment. Perfect for food truck operators, caterers, and ghost kitchens. Includes prep stations, walk-in cooler, and storage.',
    price_per_day: 2, price_per_month: 45, size_sqft: 800,
    space_type: 'commissary_kitchen', use_type: ['commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1708915965975-2a950db0e215?w=1080' }],
    amenities: { electricity: true, water_access: true, restrooms: true, parking: false, wifi: false, garbage_access: true },
    rating: 4.8, review_count: 67, instant_book: false, featured: false,
  },
  {
    id: 'ut-9',
    title: 'Spanish Fork Commissary Kitchen Space',
    city: 'Spanish Fork', state: 'UT', zip_code: '84660',
    lat: 40.1150, lng: -111.6549,
    description: 'Affordable shared kitchen space with flexible hourly rates. Equipped with ovens, grills, fryers, and all health department approved facilities. Great for startups and small food businesses.',
    price_per_day: 1, price_per_month: 35, size_sqft: 600,
    space_type: 'commissary_kitchen', use_type: ['commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1749478072094-d21cb929490c?w=1080' }],
    amenities: { electricity: true, water_access: true, restrooms: true, parking: false, wifi: false, garbage_access: true },
    rating: 4.6, review_count: 41, instant_book: true, featured: false,
  },
  {
    id: 'ut-10',
    title: 'Secure Food Truck Storage – Lehi',
    city: 'Lehi', state: 'UT', zip_code: '84043',
    lat: 40.3850, lng: -111.8650,
    description: 'Safe overnight and long-term storage for food trucks and mobile vendors. Gated facility with 24/7 security surveillance. Easy in/out access for daily operations.',
    price_per_day: 4, price_per_month: 120, size_sqft: 1500,
    space_type: 'food_truck_storage', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1578859695220-856a4f5edd39?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.8, review_count: 33, instant_book: true, featured: false,
  },
  {
    id: 'ut-11',
    title: 'Food Truck Overnight Storage',
    city: 'Orem', state: 'UT', zip_code: '84057',
    lat: 40.2888, lng: -111.6845,
    description: 'Convenient overnight parking and storage for food trucks. Secure fenced lot with power hookups for refrigeration. Month-to-month or seasonal contracts available.',
    price_per_day: 3, price_per_month: 95, size_sqft: 1000,
    space_type: 'food_truck_storage', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1619335680796-54f13b88c6ba?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.7, review_count: 19, instant_book: true, featured: false,
  },
  {
    id: 'ut-12',
    title: 'Downtown Provo Office Space',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2335, lng: -111.6610,
    description: 'Modern office space in the heart of downtown. Great for startups and small businesses. High-speed internet included.',
    price_per_day: 27, price_per_month: 800, size_sqft: 500,
    space_type: 'office', use_type: ['commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: true, parking: true, wifi: true, garbage_access: false },
    rating: 4.5, review_count: 15, instant_book: false, featured: false,
  },
  {
    id: 'ut-13',
    title: 'RV Storage – Outdoor',
    city: 'Lehi', state: 'UT', zip_code: '84043',
    lat: 40.4100, lng: -111.8700,
    description: 'Secure outdoor RV and boat storage. Gated access with security patrol. Perfect for seasonal storage.',
    price_per_day: 3, price_per_month: 85, size_sqft: 600,
    space_type: 'parking_lot', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=1080' }],
    amenities: { electricity: false, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.6, review_count: 22, instant_book: true, featured: false,
  },
  {
    id: 'ut-14',
    title: 'Small Storage Locker',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2500, lng: -111.6560,
    description: 'Compact storage locker perfect for documents, holiday decorations, or small items. Indoor climate-controlled facility.',
    price_per_day: 2, price_per_month: 45, size_sqft: 25,
    space_type: 'storage_unit', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1694601618351-dbbbb2b8934f?w=1080' }],
    amenities: { electricity: false, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.9, review_count: 38, instant_book: true, featured: false,
  },
  {
    id: 'ut-15',
    title: 'Farmers Market Vendor Booth',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2340, lng: -111.6650,
    description: 'Weekly vendor booth at popular Saturday farmers market. Ideal for artisans, farmers, and food vendors.',
    price_per_day: 2, price_per_month: 60, size_sqft: 100,
    space_type: 'mobile_vendor', use_type: ['events', 'commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.8, review_count: 42, instant_book: true, featured: false,
  },
  {
    id: 'ut-16',
    title: 'Large Warehouse – Distribution',
    city: 'Saratoga Springs', state: 'UT', zip_code: '84045',
    lat: 40.3550, lng: -111.9100,
    description: 'Massive warehouse space perfect for distribution and logistics. Multiple loading docks and office space.',
    price_per_day: 83, price_per_month: 2500, size_sqft: 5000,
    space_type: 'warehouse', use_type: ['commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1771530789155-b1f03fbf82b5?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: true, parking: true, wifi: false, garbage_access: false },
    rating: 4.7, review_count: 11, instant_book: false, featured: false,
  },
  {
    id: 'ut-17',
    title: 'Motorcycle Parking Spot',
    city: 'Orem', state: 'UT', zip_code: '84057',
    lat: 40.2920, lng: -111.6935,
    description: 'Dedicated motorcycle parking space with covered shelter. Downtown location for easy commuting.',
    price_per_day: 1, price_per_month: 40, size_sqft: 60,
    space_type: 'parking_lot', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1604063155785-ee4488b8ad15?w=1080' }],
    amenities: { electricity: false, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.5, review_count: 8, instant_book: true, featured: false,
  },
  {
    id: 'ut-18',
    title: 'Temperature-Controlled Wine Storage',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2600, lng: -111.6500,
    description: 'Premium climate-controlled storage for wine collections. Humidity and temperature monitored 24/7.',
    price_per_day: 6, price_per_month: 180, size_sqft: 80,
    space_type: 'storage_unit', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1694601618351-dbbbb2b8934f?w=1080' }],
    amenities: { electricity: false, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 5.0, review_count: 29, instant_book: true, featured: false,
  },
  {
    id: 'ut-19',
    title: 'Art Studio Space',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2390, lng: -111.6620,
    description: 'Bright studio space with natural light. Perfect for artists, photographers, or creative professionals.',
    price_per_day: 22, price_per_month: 650, size_sqft: 400,
    space_type: 'office', use_type: ['commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: false, parking: true, wifi: false, garbage_access: false },
    rating: 4.9, review_count: 17, instant_book: false, featured: false,
  },
  {
    id: 'ut-20',
    title: 'Food Truck Event – Music Festival',
    city: 'Spanish Fork', state: 'UT', zip_code: '84660',
    lat: 40.1200, lng: -111.6400,
    description: 'Premium spot at annual summer music festival. Three-day event with thousands of attendees.',
    price_per_day: 15, price_per_month: 450, size_sqft: 600,
    space_type: 'food_truck_vending', use_type: ['events', 'commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1638132704714-4156222cb2cd?w=1080' }],
    amenities: { electricity: true, water_access: true, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.8, review_count: 35, instant_book: false, featured: false,
  },
  {
    id: 'ut-21',
    title: 'Compact Storage Unit',
    city: 'American Fork', state: 'UT', zip_code: '84003',
    lat: 40.3800, lng: -111.7900,
    description: 'Small unit great for seasonal items and boxes. Easy ground floor access.',
    price_per_day: 2, price_per_month: 65, size_sqft: 50,
    space_type: 'storage_unit', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1694601618351-dbbbb2b8934f?w=1080' }],
    amenities: { electricity: false, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.4, review_count: 12, instant_book: true, featured: false,
  },
  {
    id: 'ut-22',
    title: 'Covered Garage Bay',
    city: 'Lehi', state: 'UT', zip_code: '84043',
    lat: 40.3900, lng: -111.8480,
    description: 'Single car garage with power outlet. Ideal for classic car storage.',
    price_per_day: 4, price_per_month: 120, size_sqft: 240,
    space_type: 'garage', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1758448721161-7b3df5ec04b3?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.7, review_count: 9, instant_book: true, featured: false,
  },
  {
    id: 'ut-23',
    title: 'Business Warehouse Pod',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2350, lng: -111.6850,
    description: 'Flexible warehouse pod for small businesses. Month-to-month leasing available.',
    price_per_day: 25, price_per_month: 750, size_sqft: 800,
    space_type: 'warehouse', use_type: ['commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1771530789155-b1f03fbf82b5?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.6, review_count: 14, instant_book: false, featured: false,
  },
  {
    id: 'ut-24',
    title: 'Motorcycle Storage Garage',
    city: 'Orem', state: 'UT', zip_code: '84057',
    lat: 40.2850, lng: -111.7000,
    description: 'Secure indoor motorcycle storage with maintenance area.',
    price_per_day: 3, price_per_month: 90, size_sqft: 150,
    space_type: 'garage', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1758448721161-7b3df5ec04b3?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.8, review_count: 16, instant_book: true, featured: false,
  },
  {
    id: 'ut-25',
    title: 'University Area Parking',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2500, lng: -111.6400,
    description: 'Monthly parking near BYU campus. Perfect for students and faculty.',
    price_per_day: 3, price_per_month: 75, size_sqft: 120,
    space_type: 'parking_lot', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1604063155785-ee4488b8ad15?w=1080' }],
    amenities: { electricity: false, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.3, review_count: 27, instant_book: true, featured: false,
  },
  {
    id: 'ut-26',
    title: 'Commercial Kitchen Hourly',
    city: 'Orem', state: 'UT', zip_code: '84057',
    lat: 40.2700, lng: -111.6900,
    description: 'Pay-per-hour commercial kitchen rental. All equipment included.',
    price_per_day: 1, price_per_month: 25, size_sqft: 400,
    space_type: 'commissary_kitchen', use_type: ['commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1708915965975-2a950db0e215?w=1080' }],
    amenities: { electricity: true, water_access: true, restrooms: true, parking: false, wifi: false, garbage_access: true },
    rating: 4.7, review_count: 31, instant_book: true, featured: false,
  },
  {
    id: 'ut-27',
    title: 'Extra Large Storage',
    city: 'Saratoga Springs', state: 'UT', zip_code: '84045',
    lat: 40.3400, lng: -111.9200,
    description: 'Huge storage space for large furniture, vehicles, or business inventory.',
    price_per_day: 9, price_per_month: 280, size_sqft: 600,
    space_type: 'storage_unit', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1694601618351-dbbbb2b8934f?w=1080' }],
    amenities: { electricity: false, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.6, review_count: 18, instant_book: true, featured: false,
  },
  {
    id: 'ut-28',
    title: 'Food Truck – Sports Stadium',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2400, lng: -111.6450,
    description: 'Vending spot at local sports complex during game days and tournaments.',
    price_per_day: 7, price_per_month: 200, size_sqft: 630,
    space_type: 'food_truck_vending', use_type: ['events', 'commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1638132704714-4156222cb2cd?w=1080' }],
    amenities: { electricity: true, water_access: true, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.5, review_count: 22, instant_book: false, featured: false,
  },
  {
    id: 'ut-29',
    title: 'Boat Storage – Covered',
    city: 'Saratoga Springs', state: 'UT', zip_code: '84045',
    lat: 40.3200, lng: -111.9300,
    description: 'Covered boat storage with easy trailer access. Perfect for winter storage.',
    price_per_day: 4, price_per_month: 110, size_sqft: 360,
    space_type: 'parking_lot', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=1080' }],
    amenities: { electricity: false, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.8, review_count: 24, instant_book: true, featured: false,
  },
  {
    id: 'ut-30',
    title: 'Co-Working Office Space',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2338, lng: -111.6595,
    description: 'Shared office environment with desks, WiFi, and meeting rooms.',
    price_per_day: 40, price_per_month: 1200, size_sqft: 1200,
    space_type: 'office', use_type: ['commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: true, parking: true, wifi: true, garbage_access: false },
    rating: 4.9, review_count: 56, instant_book: true, featured: true,
  },
  {
    id: 'ut-31',
    title: 'Medium Storage Unit',
    city: 'American Fork', state: 'UT', zip_code: '84003',
    lat: 40.3820, lng: -111.7880,
    description: 'Perfect size for apartment move or business files.',
    price_per_day: 4, price_per_month: 125, size_sqft: 150,
    space_type: 'storage_unit', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1694601618351-dbbbb2b8934f?w=1080' }],
    amenities: { electricity: false, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.7, review_count: 20, instant_book: true, featured: false,
  },
  {
    id: 'ut-32',
    title: 'Weekend Market Vendor Spot',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2310, lng: -111.6580,
    description: 'Saturday and Sunday vendor space at busy outdoor market.',
    price_per_day: 3, price_per_month: 80, size_sqft: 120,
    space_type: 'mobile_vendor', use_type: ['events', 'commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.4, review_count: 19, instant_book: true, featured: false,
  },
  {
    id: 'ut-33',
    title: 'Outdoor Equipment Storage',
    city: 'Lehi', state: 'UT', zip_code: '84043',
    lat: 40.4050, lng: -111.8550,
    description: 'Large garage perfect for ATVs, motorcycles, and outdoor gear.',
    price_per_day: 5, price_per_month: 160, size_sqft: 375,
    space_type: 'garage', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1758448721161-7b3df5ec04b3?w=1080' }],
    amenities: { electricity: true, water_access: true, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.9, review_count: 13, instant_book: true, featured: false,
  },
  {
    id: 'ut-34',
    title: 'Industrial Warehouse Complex',
    city: 'Pleasant Grove', state: 'UT', zip_code: '84062',
    lat: 40.3700, lng: -111.7350,
    description: 'Part of larger industrial complex with shared loading areas.',
    price_per_day: 60, price_per_month: 1800, size_sqft: 3000,
    space_type: 'warehouse', use_type: ['commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1771530789155-b1f03fbf82b5?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: false, parking: true, wifi: false, garbage_access: false },
    rating: 4.5, review_count: 10, instant_book: false, featured: false,
  },
  {
    id: 'ut-35',
    title: 'Compact Parking Space',
    city: 'Orem', state: 'UT', zip_code: '84057',
    lat: 40.2880, lng: -111.6980,
    description: 'Small car parking in secured lot. Monthly contracts available.',
    price_per_day: 2, price_per_month: 55, size_sqft: 120,
    space_type: 'parking_lot', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1604063155785-ee4488b8ad15?w=1080' }],
    amenities: { electricity: false, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.2, review_count: 15, instant_book: true, featured: false,
  },
  {
    id: 'ut-36',
    title: 'Food Prep Kitchen Space',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2250, lng: -111.6680,
    description: 'Dedicated prep space in licensed commercial kitchen.',
    price_per_day: 13, price_per_month: 400, size_sqft: 300,
    space_type: 'commissary_kitchen', use_type: ['commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1708915965975-2a950db0e215?w=1080' }],
    amenities: { electricity: true, water_access: true, restrooms: true, parking: false, wifi: false, garbage_access: true },
    rating: 4.8, review_count: 28, instant_book: false, featured: false,
  },
  {
    id: 'ut-37',
    title: 'Small Business Storage',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2650, lng: -111.6450,
    description: 'Ideal for inventory overflow and supplies.',
    price_per_day: 3, price_per_month: 95, size_sqft: 100,
    space_type: 'storage_unit', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1694601618351-dbbbb2b8934f?w=1080' }],
    amenities: { electricity: false, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.6, review_count: 21, instant_book: true, featured: false,
  },
  {
    id: 'ut-38',
    title: 'Two-Car Garage',
    city: 'Lehi', state: 'UT', zip_code: '84043',
    lat: 40.3880, lng: -111.8470,
    description: 'Spacious two-car garage with workshop area.',
    price_per_day: 7, price_per_month: 200, size_sqft: 400,
    space_type: 'garage', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1758448721161-7b3df5ec04b3?w=1080' }],
    amenities: { electricity: true, water_access: true, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.7, review_count: 11, instant_book: true, featured: false,
  },
  {
    id: 'ut-39',
    title: 'Food Truck Pod – Tech District',
    city: 'Lehi', state: 'UT', zip_code: '84043',
    lat: 40.4200, lng: -111.8700,
    description: 'Weekday lunch service location in busy tech corridor.',
    price_per_day: 9, price_per_month: 275, size_sqft: 600,
    space_type: 'food_truck_vending', use_type: ['events', 'commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1638132704714-4156222cb2cd?w=1080' }],
    amenities: { electricity: true, water_access: true, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.9, review_count: 43, instant_book: false, featured: false,
  },
  {
    id: 'ut-40',
    title: 'Climate Storage – Electronics',
    city: 'Orem', state: 'UT', zip_code: '84057',
    lat: 40.2940, lng: -111.7100,
    description: 'Temperature and humidity controlled for sensitive equipment.',
    price_per_day: 5, price_per_month: 140, size_sqft: 96,
    space_type: 'storage_unit', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1694601618351-dbbbb2b8934f?w=1080' }],
    amenities: { electricity: false, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.9, review_count: 32, instant_book: true, featured: false,
  },
  {
    id: 'ut-41',
    title: 'Trailer Parking Space',
    city: 'Spanish Fork', state: 'UT', zip_code: '84660',
    lat: 40.1050, lng: -111.6510,
    description: 'Long-term trailer and equipment parking.',
    price_per_day: 2, price_per_month: 70, size_sqft: 350,
    space_type: 'parking_lot', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1527786356703-4b100091cd2c?w=1080' }],
    amenities: { electricity: false, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.4, review_count: 14, instant_book: true, featured: false,
  },
  {
    id: 'ut-42',
    title: 'Warehouse – Light Manufacturing',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2600, lng: -111.7200,
    description: 'Warehouse with office and manufacturing capabilities.',
    price_per_day: 73, price_per_month: 2200, size_sqft: 4000,
    space_type: 'warehouse', use_type: ['commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1771530789155-b1f03fbf82b5?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: true, parking: true, wifi: false, garbage_access: false },
    rating: 4.6, review_count: 16, instant_book: false, featured: false,
  },
  {
    id: 'ut-43',
    title: 'Shared Kitchen – Weekend Use',
    city: 'American Fork', state: 'UT', zip_code: '84003',
    lat: 40.3770, lng: -111.7930,
    description: 'Weekend-only commercial kitchen access.',
    price_per_day: 12, price_per_month: 350, size_sqft: 500,
    space_type: 'commissary_kitchen', use_type: ['commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1708915965975-2a950db0e215?w=1080' }],
    amenities: { electricity: true, water_access: true, restrooms: true, parking: false, wifi: false, garbage_access: true },
    rating: 4.5, review_count: 18, instant_book: true, featured: false,
  },
  {
    id: 'ut-44',
    title: 'Drive-Up Storage Access',
    city: 'Lehi', state: 'UT', zip_code: '84043',
    lat: 40.3820, lng: -111.8650,
    description: 'Ground level with drive-up door for easy loading.',
    price_per_day: 6, price_per_month: 175, size_sqft: 300,
    space_type: 'storage_unit', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1694601618351-dbbbb2b8934f?w=1080' }],
    amenities: { electricity: false, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.8, review_count: 25, instant_book: true, featured: false,
  },
  {
    id: 'ut-45',
    title: 'Professional Office Suite',
    city: 'Orem', state: 'UT', zip_code: '84057',
    lat: 40.2780, lng: -111.6800,
    description: 'Private office with reception area and conference room.',
    price_per_day: 30, price_per_month: 900, size_sqft: 600,
    space_type: 'office', use_type: ['commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: true, parking: true, wifi: true, garbage_access: false },
    rating: 4.7, review_count: 22, instant_book: false, featured: false,
  },
  {
    id: 'ut-46',
    title: 'Mobile Vendor – Park Location',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2380, lng: -111.6640,
    description: 'Vendor space at popular city park on weekends.',
    price_per_day: 3, price_per_month: 90, size_sqft: 150,
    space_type: 'mobile_vendor', use_type: ['events', 'commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.6, review_count: 17, instant_book: true, featured: false,
  },
  {
    id: 'ut-47',
    title: 'Heated Garage Storage',
    city: 'Spanish Fork', state: 'UT', zip_code: '84660',
    lat: 40.1140, lng: -111.6350,
    description: 'Insulated and heated garage for temperature-sensitive storage.',
    price_per_day: 6, price_per_month: 185, size_sqft: 308,
    space_type: 'garage', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1758448721161-7b3df5ec04b3?w=1080' }],
    amenities: { electricity: true, water_access: true, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.9, review_count: 14, instant_book: true, featured: false,
  },
  {
    id: 'ut-48',
    title: 'Compact Warehouse Pod',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2750, lng: -111.6500,
    description: 'Small warehouse space for startups and small inventory.',
    price_per_day: 18, price_per_month: 550, size_sqft: 600,
    space_type: 'warehouse', use_type: ['commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1771530789155-b1f03fbf82b5?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.5, review_count: 12, instant_book: false, featured: false,
  },
  {
    id: 'ut-49',
    title: 'EV Charging Parking Spot',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2335, lng: -111.6570,
    description: 'Electric vehicle parking with Level 2 charging.',
    price_per_day: 4, price_per_month: 120, size_sqft: 120,
    space_type: 'parking_lot', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1604063155785-ee4488b8ad15?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.8, review_count: 29, instant_book: true, featured: false,
  },
  {
    id: 'ut-50',
    title: 'Document Storage Unit',
    city: 'Orem', state: 'UT', zip_code: '84057',
    lat: 40.3000, lng: -111.6850,
    description: 'Small climate-controlled unit perfect for business records.',
    price_per_day: 2, price_per_month: 55, size_sqft: 40,
    space_type: 'storage_unit', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1694601618351-dbbbb2b8934f?w=1080' }],
    amenities: { electricity: false, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.6, review_count: 16, instant_book: true, featured: false,
  },
  {
    id: 'ut-51',
    title: 'Food Truck – Concert Venue',
    city: 'Lehi', state: 'UT', zip_code: '84043',
    lat: 40.4150, lng: -111.8450,
    description: 'Premium location at outdoor concert venue for summer season.',
    price_per_day: 13, price_per_month: 400, size_sqft: 880,
    space_type: 'food_truck_vending', use_type: ['events', 'commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1638132704714-4156222cb2cd?w=1080' }],
    amenities: { electricity: true, water_access: true, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.9, review_count: 38, instant_book: false, featured: false,
  },
  {
    id: 'ut-52',
    title: 'Business Inventory Storage',
    city: 'Orem', state: 'UT', zip_code: '84057',
    lat: 40.2780, lng: -111.7050,
    description: 'Large unit designed for e-commerce and retail inventory.',
    price_per_day: 8, price_per_month: 225, size_sqft: 375,
    space_type: 'storage_unit', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1694601618351-dbbbb2b8934f?w=1080' }],
    amenities: { electricity: false, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.7, review_count: 23, instant_book: true, featured: false,
  },
  {
    id: 'ut-53',
    title: 'Commercial Kitchen – Night Shift',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2800, lng: -111.6400,
    description: 'Late night kitchen access for ghost kitchens and delivery services.',
    price_per_day: 17, price_per_month: 500, size_sqft: 450,
    space_type: 'commissary_kitchen', use_type: ['commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1708915965975-2a950db0e215?w=1080' }],
    amenities: { electricity: true, water_access: true, restrooms: true, parking: false, wifi: false, garbage_access: true },
    rating: 4.6, review_count: 21, instant_book: false, featured: false,
  },
  {
    id: 'ut-54',
    title: 'Workshop Garage Space',
    city: 'American Fork', state: 'UT', zip_code: '84003',
    lat: 40.3850, lng: -111.7900,
    description: 'Garage with workbench and tool storage. Great for hobbyists.',
    price_per_day: 5, price_per_month: 145, size_sqft: 320,
    space_type: 'garage', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1758448721161-7b3df5ec04b3?w=1080' }],
    amenities: { electricity: true, water_access: true, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.7, review_count: 13, instant_book: true, featured: false,
  },
  {
    id: 'ut-55',
    title: 'Oversized Parking Bay',
    city: 'Lehi', state: 'UT', zip_code: '84043',
    lat: 40.3850, lng: -111.8580,
    description: 'Extra wide parking for large trucks or multiple vehicles.',
    price_per_day: 5, price_per_month: 140, size_sqft: 240,
    space_type: 'parking_lot', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1604063155785-ee4488b8ad15?w=1080' }],
    amenities: { electricity: false, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.5, review_count: 11, instant_book: true, featured: false,
  },
  {
    id: 'ut-56',
    title: 'Tech Startup Office',
    city: 'Lehi', state: 'UT', zip_code: '84043',
    lat: 40.4250, lng: -111.8650,
    description: 'Modern office space perfect for tech companies.',
    price_per_day: 37, price_per_month: 1100, size_sqft: 800,
    space_type: 'office', use_type: ['commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: true, parking: true, wifi: true, garbage_access: false },
    rating: 4.9, review_count: 34, instant_book: false, featured: false,
  },
  {
    id: 'ut-57',
    title: 'Weekend Vendor – Shopping Center',
    city: 'Orem', state: 'UT', zip_code: '84057',
    lat: 40.2850, lng: -111.6920,
    description: 'High-traffic vendor spot at busy shopping center.',
    price_per_day: 4, price_per_month: 110, size_sqft: 144,
    space_type: 'mobile_vendor', use_type: ['events', 'commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: false, parking: true, wifi: false, garbage_access: false },
    rating: 4.6, review_count: 19, instant_book: true, featured: false,
  },
  {
    id: 'ut-58',
    title: 'Furniture Storage Unit',
    city: 'Saratoga Springs', state: 'UT', zip_code: '84045',
    lat: 40.3480, lng: -111.9150,
    description: 'Large unit perfect for furniture and household goods.',
    price_per_day: 5, price_per_month: 155, size_sqft: 200,
    space_type: 'storage_unit', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1694601618351-dbbbb2b8934f?w=1080' }],
    amenities: { electricity: false, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.8, review_count: 26, instant_book: true, featured: false,
  },
  {
    id: 'ut-59',
    title: 'Distribution Warehouse',
    city: 'Orem', state: 'UT', zip_code: '84057',
    lat: 40.2750, lng: -111.7100,
    description: 'Large warehouse with dock-high loading and ample parking.',
    price_per_day: 107, price_per_month: 3200, size_sqft: 6000,
    space_type: 'warehouse', use_type: ['commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1771530789155-b1f03fbf82b5?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: true, parking: true, wifi: false, garbage_access: false },
    rating: 4.7, review_count: 15, instant_book: false, featured: false,
  },
  {
    id: 'ut-60',
    title: 'Food Truck Storage Bay',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2150, lng: -111.6670,
    description: 'Dedicated food truck storage with wash station.',
    price_per_day: 5, price_per_month: 135, size_sqft: 1260,
    space_type: 'food_truck_storage', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1578859695220-856a4f5edd39?w=1080' }],
    amenities: { electricity: true, water_access: true, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.8, review_count: 22, instant_book: true, featured: false,
  },
  {
    id: 'ut-61',
    title: 'Midsize Storage Unit',
    city: 'Spanish Fork', state: 'UT', zip_code: '84660',
    lat: 40.1160, lng: -111.6600,
    description: 'Good size for moving or business archive storage.',
    price_per_day: 4, price_per_month: 110, size_sqft: 120,
    space_type: 'storage_unit', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1694601618351-dbbbb2b8934f?w=1080' }],
    amenities: { electricity: false, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.5, review_count: 18, instant_book: true, featured: false,
  },
  {
    id: 'ut-62',
    title: 'Commissary Kitchen – Baking Focus',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2200, lng: -111.6450,
    description: 'Commercial kitchen with bakery equipment and ovens.',
    price_per_day: 20, price_per_month: 600, size_sqft: 550,
    space_type: 'commissary_kitchen', use_type: ['commercial'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1749478072094-d21cb929490c?w=1080' }],
    amenities: { electricity: true, water_access: true, restrooms: true, parking: false, wifi: false, garbage_access: true },
    rating: 4.9, review_count: 27, instant_book: false, featured: false,
  },
  {
    id: 'ut-63',
    title: 'Secure Garage – Collector Cars',
    city: 'Pleasant Grove', state: 'UT', zip_code: '84062',
    lat: 40.3700, lng: -111.7380,
    description: 'Premium garage with alarm and climate control for collector vehicles.',
    price_per_day: 8, price_per_month: 250, size_sqft: 432,
    space_type: 'garage', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1758448721161-7b3df5ec04b3?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 5.0, review_count: 19, instant_book: true, featured: false,
  },
  {
    id: 'ut-64',
    title: 'Downtown Covered Parking',
    city: 'Provo', state: 'UT', zip_code: '84601',
    lat: 40.2337, lng: -111.6598,
    description: 'Premium covered parking in downtown core.',
    price_per_day: 3, price_per_month: 95, size_sqft: 120,
    space_type: 'parking_lot', use_type: ['personal'],
    images: [{ image_url: 'https://images.unsplash.com/photo-1604063155785-ee4488b8ad15?w=1080' }],
    amenities: { electricity: true, water_access: false, restrooms: false, parking: false, wifi: false, garbage_access: false },
    rating: 4.7, review_count: 31, instant_book: true, featured: false,
  },
];
